### ISSUE TITLE
关于接口/api/sensitiveWord/tags

### ISSUE THREAD

**Issue by XueJiaMeng** [houbb/sensitive-word-admin#1]
服务拉起来后 我在测试/api/sensitiveWord/tags这个接口的时候返回的结果为空 
![返回结果截图](https://github.com/user-attachments/assets/bf552beb-60f7-411b-963e-494d7da55b1e)
这里是自定义的标签 测试接口返回结果仍旧为空
![自定义的标签](https://github.com/user-attachments/assets/94b38c20-0d37-45a2-9311-04abaae97b5c)

**Comment by houbb** [comment]
SensitiveWordConfig 中并没有指定对应的 tags 相关的信息。

默认的配置实现为空 `WordTags.none();`

可以自行配置一下。

**Comment by houbb** [comment]
v1.4.0 最新代码默认添加了，怎么使用 参见 [如何自定义标签](https://github.com/houbb/sensitive-word-admin?tab=readme-ov-file#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8D%95%E8%AF%8D-tag)
